Mv3
GoogleChrome/web-vitals-extension pull request #87
Opened 2021-04-22 20:16 UTC by jeremyriverain

Hello,

In order to better understand the implications of the new manifest V3, I made the effort to migrate from version 2 to version 3. 
Perhaps this work is a bit premature, given the recent publication of the new manifest. 
Anyway, I post here the result of my work, in case you are interested in some parts.

Regards.
Jérémy Riverain

2021-04-22 20:34 UTC, jeremyriverain commented
@googlebot I signed it!

2022-05-04 18:16 UTC, rviscomi commented
Thank you for working on this @jeremyriverain! Sorry for the delay. If you're still interested, could you sync to the latest version and resolve the merge conflicts? If not I'm happy to pick up any remaining work on this PR. It'd be great to complete the Manifest v3 migration soon, as I understand we're [running out of time](https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/).

2022-05-04 19:02 UTC, jeremyriverain commented
@rviscomi sure i can work on it. It would be a pleasure to contribute. 

Just give me a few days to find a moment and understand the changes to the repository since the last time.

2022-05-07 12:36 UTC, jeremyriverain commented
I rebased this branch on the master branch. There were only minor conflicts in the `manifest.json` file.

It seems that the extension works as before. That said, as I'm not the maintainer of the repo, I can't be sure.

Can you look at this work and tell me what you think please ? Is there anything I can do ?

2022-05-09 17:07 UTC, rviscomi commented
Thank you @jeremyriverain! I've tested your branch locally and the extension appears to be working correctly. I'll go through the code more closely and leave any feedback.

2022-05-09 17:41 UTC, rviscomi requested changes

2022-05-09 17:41 UTC, rviscomi commented on manifest.json
>      "https://www.googleapis.com/pagespeedonline/v5/runPagespeed?*"
Can we collapse everything into this single pattern?

https://developer.chrome.com/docs/extensions/mv3/match_patterns/

```suggestion
    "*://*/*"
```

2022-05-09 17:41 UTC, rviscomi commented on manifest.json
> +    "extensions": "script-src 'self' https://www.googleapis.com; object-src 'self'"
A few of changes:

- the property should be `extension_pages` per https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#content-security-policy
- use the `default-src 'self'` catch-all directive
- use the CrUX-specific host for the `connect-src` directive

```suggestion
    "extension_pages": "default-src 'self'; connect-src https://chromeuxreport.googleapis.com;"
```

2022-05-09 17:41 UTC, rviscomi commented on manifest.json
> +      "matches": ["https://*/*", "http://*/*"]
```suggestion
      "matches": ["*://*/*"]
```

2022-05-09 17:41 UTC, rviscomi commented on manifest.json
> +        "/node_modules/web-vitals/dist/web-vitals.js"
Doesn't seem like we're using the `node_modules` version for now, but we should probably fix that soon.

```suggestion
        "src/browser_action/web-vitals.js"
```

2022-05-09 22:21 UTC, rviscomi commented
Woohoo thanks @jeremyriverain! I changed the destination branch from `master` to a new one named `manifest-v3`. We just released v1.1.1 to the store yesterday, and I'm anticipating that we may need to push some higher priority bug fixes in the coming weeks. Decoupling these changes from `master` lets us publish bug fixes without risking more issues caused by the v3 migration.

2022-05-09 22:22 UTC, rviscomi approved these changes

2022-05-09 22:22 UTC, merged